const PROSPECTS = [
  ["Jeremiah Smith","WR","Ohio State",1,98,"Elite WR prospect with rare size and ball skills."],
  ["Arch Manning","QB","Texas",2,96,"High-upside passer with NFL bloodlines and arm talent."],
  ["Colin Simmons","EDGE","Texas",3,95,"Explosive edge rusher with burst and bend."],
  ["Dante Moore","QB","Oregon",4,94,"Accurate passer with starter traits."],
  ["Caleb Downs","S","Ohio State",5,94,"Do-it-all safety with range and instincts."],
  ["Julian Sayin","QB","Ohio State",6,93,"Quick processor with accuracy and touch."],
  ["David Stone","DL","Oklahoma",7,92,"Interior disruptor with power and pass-rush upside."],
  ["Francis Mauigoa","OT","Miami",8,92,"Powerful tackle with size and movement skills."],
  ["Rueben Bain Jr.","EDGE","Miami",9,91,"Versatile front defender with strength and production."],
  ["KJ Bolden","S","Georgia",10,91,"Athletic safety with coverage versatility."],
  ["Ryan Wingo","WR","Texas",11,90,"Big-play receiver with vertical ability."],
  ["Cam Coleman","WR","Auburn",12,90,"Long receiver with red-zone upside."],
  ["Peter Woods","DL","Clemson",13,89,"Powerful interior defender with disruption ability."],
  ["Anthony Hill Jr.","LB","Texas",14,89,"Fast downhill linebacker with blitz value."],
  ["Carnell Tate","WR","Ohio State",15,88,"Smooth receiver with strong hands."],
  ["TJ Parker","EDGE","Clemson",16,88,"High-motor edge with power."],
  ["Spencer Fano","OT","Utah",17,87,"Technically sound tackle prospect."],
  ["Monroe Freeling","OT","Georgia",18,87,"Long tackle with developmental upside."],
  ["Dylan Raiola","QB","Nebraska",19,86,"Talented passer with arm strength."],
  ["Zachariah Branch","WR","Georgia",20,86,"Electric slot and return weapon."],
  ["Kenyon Sadiq","TE","Oregon",21,85,"Athletic receiving tight end."],
  ["Jermod McCoy","CB","Tennessee",22,85,"Smooth corner with ball skills."],
  ["Sonny Styles","LB","Ohio State",23,84,"Hybrid defender with size and speed."],
  ["Olaivavega Ioane","IOL","Penn State",24,84,"Powerful interior blocker."],
  ["Dillon Thieneman","S","Oregon",25,83,"Instinctive safety with production."],
  ["Kadyn Proctor","OT","Alabama",26,83,"Massive tackle with rare size."],
  ["Makai Lemon","WR","USC",27,82,"Sharp route-runner with YAC ability."],
  ["Parker Brailsford","IOL","Alabama",28,82,"Athletic interior lineman."],
  ["Sam Leavitt","QB","Arizona State",29,81,"Mobile QB with off-platform ability."],
  ["Bryant Wesco Jr.","WR","Clemson",30,81,"Explosive outside receiver."],
  ["Leonard Moore","CB","Notre Dame",31,80,"Long corner with press tools."],
  ["Nicholas Marsh","WR","Michigan State",32,80,"Big-bodied contested-catch target."],
  ["Mansoor Delane","CB","LSU",33,79,"Outside corner with length."],
  ["CJ Baxter","RB","Texas",34,79,"Three-down RB profile."],
  ["LT Overton","EDGE","Alabama",35,78,"Big edge defender with power."],
  ["Drew Allar","QB","Penn State",36,78,"Big-armed passer with NFL frame."],
  ["Justice Haynes","RB","Michigan",37,77,"Explosive runner with receiving upside."],
  ["Matayo Uiagalelei","EDGE","Oregon",38,77,"Long edge with power traits."],
  ["Eugene Wilson III","WR","Florida",39,76,"Quick separator with slot value."],
  ["Jaeden Roberts","IOL","Alabama",40,76,"Physical guard prospect."]
].map(p => ({
  name:p[0], pos:p[1], school:p[2], rank:p[3], grade:p[4], summary:p[5]
}));
